name: deploy-on-release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - run: cp package.json pnpm-lock.yaml dist

      - name: Deploy to server
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avz --delete --exclude='.env' --exclude='database.db' --exclude='node_modules'
          path: dist/
          remote_path: ${{ vars.SSH_TARGET_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_DEPLOY_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}

      - name: Install dependencies on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ vars.TARGET_DIR }}
            pnpm install --frozen-lockfile --prod
